# Generated by Django 5.0.6 on 2024-05-30 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('elevation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('spring', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('summer', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], default='1A', max_length=2)),
                ('autumn', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('1Б', '1Б'), ('2Б', '2Б'), ('3Б', '3Б')], default='1A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('other_titles', models.CharField(max_length=128)),
                ('connect', models.CharField(max_length=128)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NW', 'new'), ('PN', 'pending'), ('AC', 'accepted'), ('RJ', 'rejected')], default='NW', max_length=2)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DBpereval.coordinates')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBpereval.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBpereval.tourist')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=128)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DBpereval.pereval')),
            ],
        ),
    ]
